### ISSUE TITLE
Subscriptions never reconnect after ConnectionLost

### ISSUE THREAD

**Issue by Trapoh** [JKorf/Bittrex.Net#136]
Hello,
First of all, thank you for your hard work.

I have updated the package through NuGet and i noticed that when a Subscription is disconnected, it never get connected again. Anyone having this behavior ?

I was using the november version and everything was fine.

i'm using this :
 var subscriptionMarket = await socketClient.SubscribeToMarketSummariesUpdateAsync

and subscriptionMarket.Data.ConnectionLost (which is fired)
and subscriptionMarket.Data.ConnectionRestored (which is never fired)

any idea ? 

Thank you guys, Merry Christmas and happy new year

**Comment by molnarr2** [comment]
Same issue here. The reconnect interval is default set to 5 seconds. Thanks for the hard work on this.

**Comment by Trapoh** [comment]
Hello,

I hope it will help :

**Right after i cut my internet : it says : "Impossible to read transport connection data....**
2018/12/29 11:37:30:177 | Warning | Socket 1 error: System.IO.IOException: Impossible de lire les données de la connexion de transport : Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte. ---> System.Net.Sockets.SocketException: Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte.

**Then :** 
 à System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   à System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   à SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
2018/12/29 11:37:30:243 | Info | Socket 1 Connection lost, will try to reconnect

But it never reconnect...

Thank you in advance !

**Comment by JKorf** [comment]
Thats to be expected when internet is down, after that it should indeed reconnect. Can you put LogVerbosity on Debug in the BittrexClientOptions so I can see some more details? I'm mostly interested in what happens after this bit

**Comment by JKorf** [comment]
Never mind, I've identified the issue. Will fix this for next release.

**Comment by Trapoh** [comment]
Sorry for late reply.

I do have activated LogVerbosity.Info but it's all i got in debugger.

I have tried your new release and it seems to reconnect now :
2018/12/29 16:05:24:183 | Info | Socket 3 Connection lost, will try to reconnect
2018/12/29 16:05:30:206 | Info | Socket 3 reconnected after 00:00:06.0215565
2018/12/29 16:05:30:369 | Info | Socket 3 successfully resubscribed


Thank you very much, happy new year. Health and wealth to you and your family.

**Comment by Trapoh** [comment]
Hello again, 

i'm getting this kind of error, i guess i'm missing something : 

2018/12/29 17:44:31:301 | Warning | Socket 89 error: System.InvalidOperationException: Socket closed
2018/12/29 17:44:31:333 | Warning | Failed to invoke proxy: Socket closed
2018/12/29 17:44:31:362 | Warning | Socket 173 error: System.InvalidOperationException: Socket closed
2018/12/29 17:44:31:395 | Warning | Failed to invoke proxy: Socket closed
2018/12/29 17:44:31:427 | Warning | Socket 261 error: System.InvalidOperationException: Socket closed
2018/12/29 17:44:31:453 | Warning | Failed to invoke proxy: Socket closed
2018/12/29 17:44:41:990 | Info | Socket 317 closed
2018/12/29 17:44:42:001 | Warning | Failed to invoke proxy: Connection was disconnected before invocation result was received.
2018/12/29 17:44:42:640 | Info | Socket 261 closed
2018/12/29 17:44:42:642 | Info | Socket 217 closed
2018/12/29 17:44:42:643 | Warning | Failed to invoke proxy: Connection was disconnected before invocation result was received.
2018/12/29 17:44:42:796 | Info | Socket 185 closed
2018/12/29 17:44:42:796 | Info | Socket 173 closed
2018/12/29 17:44:42:796 | Info | Socket 155 closed
2018/12/29 17:44:42:839 | Info | Socket 93 closed
2018/12/29 17:44:42:888 | Warning | Failed to invoke proxy: Connection was disconnected before invocation result was received.
2018/12/29 17:44:42:888 | Warning | Failed to invoke proxy: Connection was disconnected before invocation result was received.
2018/12/29 17:44:42:897 | Warning | Failed to invoke proxy: Connection was disconnected before invocation result was received.
2018/12/29 17:44:42:818 | Info | Socket 103 closed
2018/12/29 17:44:42:905 | Warning | Failed to invoke proxy: Connection was disconnected before invocation result was received.
2018/12/29 17:44:42:839 | Info | Socket 89 closed


Then i get this kind of error "Timeout" and it never reconnect  : 
2018/12/29 17:46:07:094 | Info | Socket 327 Connection lost, will try to reconnect
2018/12/29 17:46:07:117 | Info | Socket 311 Connection lost, will try to reconnect
2018/12/29 17:46:07:117 | Info | Socket 297 Connection lost, will try to reconnect
2018/12/29 17:46:07:487 | Info | Socket 281 Connection lost, will try to reconnect
2018/12/29 17:46:08:485 | Warning | Socket 189 error: System.TimeoutException: The client has been inactive since 29/12/2018 16:44:41 and it has exceeded the inactivity timeout of 00:00:50. Stopping the connection.

Is there a limit of subscriptions ? it seems to work well with a couple of market subscription but not when subscribing to 200 pairs.

**Comment by Trapoh** [comment]
**Though, after a couple of minutes, i get subscription reconnect :** 

2018/12/29 17:50:02:014 | Info | Socket 215 successfully resubscribed
2018/12/29 17:50:01:977 | Info | Socket 79 successfully resubscribed
2018/12/29 17:50:01:975 | Info | Socket 363 successfully resubscribed
2018/12/29 17:50:02:152 | Info | Socket 231 successfully resubscribed
2018/12/29 17:50:01:998 | Info | Socket 69 successfully resubscribed
2018/12/29 17:50:02:169 | Info | Socket 265 reconnected after 00:01:54.6523418
2018/12/29 17:50:02:105 | Info | Socket 229 reconnected after 00:01:48.6083373
2018/12/29 17:50:02:200 | Info | Socket 323 reconnected after 00:03:54.9686554

**Comment by Trapoh** [comment]
Well it's my fault, i guess it's all right but i don't how to program correctly... 

Thank you again, Happy new year guys.

**Comment by pwnzya** [comment]
Hello,

Just wanted to say that the new release 3.0.3 isn't available from NuGet yet after 4 days.
As for reconnects taking a few minutes, maybe it is related to #135.

Wishing you a happy new year!

**Comment by JKorf** [comment]
Happy new year to you too guys.

I think you're right @pwnzya, with 100+ subscriptions the reconnecting takes a pretty long time. I'll look to solve this #135.

Also I think I might have forgotten to actually push the 3.0.3 version, I've done that now.

**Comment by molnarr2** [comment]
Thanks! I'll give the latest nuget a try.

**Comment by mclean25** [comment]
Has anyone noticed that this should be resolved now? Trying to think of how to quickly test this. I guess pulling the internet is the best thing I can think of right now.

**Comment by Trapoh** [comment]
I do believe it is resolved since v3.0.4. I do have tested it the same way, by cutting my internet. Thank you JKorf.

**Comment by mclean25** [comment]
@JKorf I'm still getting issues on this even after updating to v3.0.4. It seems like if I disconnect my internet and plug it back in it works, but if I leave it running for say half a day, it doesn't seem to reconnnect. Not sure what to do at this point but just notifying that this issue is not resolved.
