### ISSUE TITLE
Could not connect to Bittrex server

### ISSUE THREAD

**Issue by wklm** [JKorf/Bittrex.Net#5]
Hey @JKorf , 

first of all many thanks for making this project public. I was trying it out with the example code. The REST part works fine, but I have a problem with signalr client. 

While I'm trying to run this:

```
using System;
using Bittrex.Net;
using Bittrex.Net.Logging;


namespace Examples
{
    class Program
    {
        static void Main(string[] args)
        {
            BittrexDefaults.SetDefaultApiCredentials("***", "***");
            BittrexDefaults.SetDefaultLogOutput(Console.Out);
            BittrexDefaults.SetDefaultLogVerbosity(LogVerbosity.Debug);

            var socketClient = new BittrexSocketClient();
            var subcribtion = socketClient.SubscribeToMarketDeltaStream("BTC-ETH",
                summary => { Console.WriteLine($"BTC-ETH: {summary.Last}"); });
                      
            Console.ReadLine();
            socketClient.UnsubscribeFromStream(subcribtion.Result);

        }
    }
}
```

I'm getting this output:

```
01:29:38:783 | Debug | Going to subscribe to BTC-ETH
01:29:38:800 | Debug | Starting connection to bittrex server
01:29:38:806 | Debug | Socket state: Disconnected -> Connecting
01:29:39:058 | Debug | Socket state: Connecting -> Disconnected
01:29:39:065 | Debug | Socket closed
01:29:39:067 | Warning | Call failed: Could not connect to Bittrex server
```

Could you give me some tips what am I doing wrong?

Cheers,
Wojtek

**Comment by wklm** [comment]
Shouldn't it be `http://socket.bittrex.com/signalr` instead of `https://www.bittrex.com/` here?
https://github.com/JKorf/Bittrex.Net/blob/master/Bittrex.Net/BittrexSocketClient.cs#L20

**Comment by JKorf** [comment]
Hi, thanks for contacting me. Currently Bittrex enabled Cloudflare protection. They do this to help versus DDOS attacks. This prevents the SignalR socket from connecting directly. 

I'm in the process of making a fix which will work with the Cloudflare protection, should be able to push that in about an hour I think.

The link is okay btw, the SignalR client internally gets the socket url from the base bittrex.com url irc.

**Comment by wklm** [comment]
awesome, thanks a lot!

**Comment by wklm** [comment]
You might want to take a look on that: https://github.com/elcattivo/CloudFlareUtilities

**Comment by JKorf** [comment]
That's indeed the utility I've added. I just released an update which should fix the issues. (might take a little while before it shows the new version in the nuget package manager)

**Comment by wklm** [comment]
after upgrading the package to the latest version I'm still getting the same error:

```
03:59:59:486 | Debug | Going to subscribe to BTC-ETH
03:59:59:491 | Debug | Starting connection to bittrex server
04:00:05:096 | Debug | Socket state: Disconnected -> Connecting
04:00:05:386 | Debug | Socket state: Connecting -> Disconnected
04:00:05:392 | Debug | Socket closed
04:00:05:403 | Warning | Call failed: Could not connect to Bittrex server
```

Here's my `.csproj` 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bittrex.Net" Version="1.1.3" />
    <PackageReference Include="CloudFlareUtilities" Version="0.1.0.2" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>
</Project>
```

**Comment by wklm** [comment]
When I upgrade the `CloudFlareUtilities` to the latest version (0.5.0-alpha) I'm getting:

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void CloudFlareUtilities.ClearanceHandler..ctor(System.Net.Http.HttpClientHandler)'.
   at Bittrex.Net.BittrexSocketClient.TryGetCloudFlareAccess(Int32 currentTry)
   at Bittrex.Net.BittrexSocketClient.WaitForConnection()
   at Bittrex.Net.BittrexSocketClient.SubscribeToMarketDeltaStream(String marketName, Action`1 onUpdate)

```

**Comment by wklm** [comment]
I tried running it as net46 instead of dotnetcore2 and it worked. I'm not sure why is it so, everything seems to be compatible with dotnet standard...

**Comment by JKorf** [comment]
I've been able to replicate the issue and I came to the same conclusion, when targeting .net core2 it fails. I will look into this and try to find the underlying issue, but can't provide a quick fix for you right now, sorry!

I created a new Issue for this. #6

**Comment by wklm** [comment]
thanks a lot :)
