### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by pwnzya** [JKorf/Bittrex.Net#77]
Hello.

With the latest version of Bittrex.Net (2.0.4) and CryptoExchange.Net (0.0.8), SubscribeToExchangeDeltasAsync fails to connect to Bittrex server.
(It could connect to the server with version Bittrex.Net v2.0.3 and CryptoExchange.Net v0.0.7)

Code:
```
var client = new BittrexSocketClient();
var result = await Task.Run(() =>
{
  return client.SubscribeToExchangeDeltasAsync(marketName, data => Handler(data));
}).ConfigureAwait(false);
```
Error:
```
Success = false
Error.Message = Can't connect to the server
```
Log (with LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Debug):
```
01:39:31:768 | Warning | Couldn't connect. System.MissingMethodException
01:39:31:768 | Debug |  Missing method: 'System.Threading.Tasks.Task`1<Boolean> WebSocket4Net.WebSocket.OpenAsync()'
```
By the way, SubscribeToExchangeDeltasAsync still freezes when called from UI thread without Task.Run thing.

**Comment by JKorf** [comment]
Thanks for letting me know. I actually pushed a new version which should fix the connection issue, but nuget is being quite slow today. Could come online any minute. I'll look into the freeze

**Comment by JKorf** [comment]
Can you try with the latest version? It's on Nuget now.

**Comment by pwnzya** [comment]
Thanks for quick reply :)
I tried the new version 2.0.5 and it is working fine now. Thanks.
The freezing issue is still there though.

**Comment by JKorf** [comment]
No problem. Fix for freezing will probably get pushed tomorrow.

**Comment by pwnzya** [comment]
OK. Thanks.
Closing this thread as the main issue was fixed.
